image: sbtscala/scala-sbt:openjdk-17.0.2_1.8.1_2.13.10

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - sbt compile

parser-test-job:
  stage: test
  script:
    - sbt "testOnly wacc.ParserTests"

parser-basic-test:
  stage: test
  script:
    - sbt "testOnly wacc.basicTest"

parser-advanced-test:
  stage: test
  script:
    - sbt "testOnly wacc.functionTest"
    - sbt "testOnly wacc.arrayTest"
    - sbt "testOnly wacc.pairTest"
    - sbt "testOnly wacc.errorTest"

parser-semantic-test:
  stage: test
  script:
    - sbt "testOnly wacc.arraySemanticTest"
    - sbt "testOnly wacc.exitTest"
    - sbt "testOnly wacc.ioTest"
    - sbt "testOnly wacc.multipeTest"
    - sbt "testOnly wacc.readTest"
