image: sbtscala/scala-sbt:openjdk-17.0.2_1.8.1_2.13.10

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - sbt compile

build-vm:
  tags:
    - group32
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - sbt compile

parser-test-job:
  stage: test
  script:
    - sbt "testOnly wacc.ParserTest"
    - sbt "testOnly wacc.basicTest"
    - sbt "testOnly wacc.functionTest"
    - sbt "testOnly wacc.arrayTest"
    - sbt "testOnly wacc.pairTest"
    - sbt "testOnly wacc.arraySemanticTest"
    - sbt "testOnly wacc.exitTest"
    - sbt "testOnly wacc.IOTest"
    - sbt "testOnly wacc.multipleTest"
    - sbt "testOnly wacc.readTest"

error-test:
  stage: test
  script: 
    - sbt "testOnly wacc.errorTest"

codegen-test:
  tags:
    - group32
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - sbt "testOnly wacc.CodeGenTest"

stlib-test-job:
  tags:
    - group32
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - sbt "testOnly wacc.StLibTest"

optimise-test:
  tags:
    - group32
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - sbt "testOnly wacc.OptimiseTest"        


